### ISSUE TITLE
py:switch always outputs the content of py:else

### ISSUE THREAD

**Issue by scmmmh** [nandoflorestan/kajiki#17]
Hi,

I've run into a problem with the py:switch code. If I define a py:switch with more than two py:case and then a py:else, the content of the py:else is always output, except if the final py:case is True.

```python
txt = u'''<div>
<py:switch test="category">
  <py:case value="'a'">A</py:case>
  <py:case value="'b'">B</py:case>
  <py:else>O</py:else>
</py:switch>
</div>'''
tmpl = XMLTemplate(txt)
```

With that base code

```python
tmpl({'category': 'a'}).render()
```

should output "<div>A</div>", but outputs "<div>AO</div>". However

```python
tmpl({'category': 'b'}).render()
```

correctly outputs "<div>B</div>" as it should. It seems that only the last py:case is being considered to determine whether to run the py:else. Possibly all py:case are outputting "if(condition)" rather than "elif(condition)" for everything but the first py:case.

**Comment by amol-** [comment]
Looks like it's exactly as you predicted: https://github.com/nandoflorestan/kajiki/blob/master/kajiki/ir.py#L257-L258

`py:case` always emits an `if` condition

**Comment by amol-** [comment]
https://github.com/nandoflorestan/kajiki/commit/1c4667dfdad824d93ef2f81cee2c453229beab0e should provide a simple fix to the issue without having to track number of `py:case` nodes

**Comment by scmmmh** [comment]
An elegant fix and the performance impact of the first if False should be minimal. Thank you.
