### ISSUE TITLE
Kajiki splits text blocks apart into individual lines for translating 

### ISSUE THREAD

**Issue by nphilipp** [nandoflorestan/kajiki#21]
When I extract translatable strings from templates, Kajiki splits text blocks into individual lines (destroying paragraph context). Take a template containing a paragraph like this one:

    ...
      <p>
        A cookie is a small text file that a website saves on your computer or
        mobile device when you visit the site. It enables the website to remember
        your actions and preferences (such as login, language, font size and
        other display preferences) over a period of time, so you don’t have to
        keep re-entering them whenever you come back to the site or browse from
        one page to another.
      </p>
    ...

Here's what `python setup.py extract_messages` produces with Genshi:

    ...
    #: project/templates/cookies.html:19
    msgid ""
    "A cookie is a small text file that a website saves on your computer or\n"
    "    mobile device when you visit the site. It enables the website to "
    "remember\n"
    "    your actions and preferences (such as login, language, font size and\n"
    "    other display preferences) over a period of time, so you don’t have to\n"
    "    keep re-entering them whenever you come back to the site or browse from\n"
    "    one page to another."
    msgstr ""
    ...

The whitespace and newlines aren't that pretty, but it's one continuous string. Here's what Kajiki makes of it:

    ...
    #: project/templates/cookies.xhtml:18
    msgid "    A cookie is a small text file that a website saves on your computer or"
    msgstr ""

    #: project/templates/cookies.xhtml:19
    msgid "    mobile device when you visit the site. It enables the website to remember"
    msgstr ""

    #: project/templates/cookies.xhtml:20
    msgid "    your actions and preferences (such as login, language, font size and"
    msgstr ""

    #: project/templates/cookies.xhtml:21
    msgid "    other display preferences) over a period of time, so you don’t have to"
    msgstr ""

    #: project/templates/cookies.xhtml:22
    msgid "    keep re-entering them whenever you come back to the site or browse from"
    msgstr ""

    #: project/templates/cookies.xhtml:23
    msgid "    one page to another."
    msgstr ""
    ...

Tools like poedit don't honor the order in which msgids are in a PO file. That really makes it unusable for me. :(

**Comment by amol-** [comment]
Seems https://github.com/nandoflorestan/kajiki/pull/20 seems to do what you expect, but even when applying those changes the nodes are then split again by the extractor itself ( https://github.com/nandoflorestan/kajiki/blob/master/kajiki/i18n.py#L28 ).

I don't know why this was explicitly intended, but maybe @rick446 remembers the specific reason why he did it.

I would like to ensure we don't break any other behaviour by removing line splitting in the extractor.

**Comment by nphilipp** [comment]
I tried @scmmmh's patches and added one of my own on top:

```
From f7bd51dace0959268128e82676bc3857da3718ef Mon Sep 17 00:00:00 2001
From: Nils Philippsen <nils@tiptoe.de>
Date: Wed, 31 Aug 2016 11:10:55 +0200
Subject: [PATCH] preserve multi-line paragraphs when extracting

---
 kajiki/i18n.py | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/kajiki/i18n.py b/kajiki/i18n.py
index e7d54cc..37390c0 100644
--- a/kajiki/i18n.py
+++ b/kajiki/i18n.py
@@ -25,5 +25,4 @@ def extract(fileobj, keywords, comment_tags, options):
     for node in ir:
         if isinstance(node, TranslatableTextNode):
             if node.text.strip():
-                for line in node.text.split('\n'):
-                    yield (node.lineno, '_', line, [])
+                yield (node.lineno, '_', node.text.strip(), [])
-- 
2.7.4
```

This works as far as extraction goes, this paragraph…:

```
  <p>
    To make this site work properly, we sometimes place small data files
    called cookies on your device. Most big websites do this too.
  </p>
```

…becomes this in the POT file:

```
#: igl/templates/cookies.xhtml:11
msgid ""
"To make this site work properly, we sometimes place small data files\n"
"    called cookies on your device. Most big websites do this too."
msgstr ""
```

Unfortunately, the paragraph doesn't get translated when accessing the page, probably because it still attempts to look up individual lines and not the whole block of text for translation.

**Comment by amol-** [comment]
Translation is performed by the `TranslatableTextNode`, so having a single `TranslatableTextNode` should lead to the whole paragraph being translate. It might be something related to matching the content with the msgid (maybe escaping? You `strip()` in your patch, maybe it doesn't match anymore?)

**Comment by nphilipp** [comment]
Ahh right, my bad. Works for me with this patch instead:

```
From 7e4b61fe44ad85e39e6ebbfc5a5b9f75484df89d Mon Sep 17 00:00:00 2001
From: Nils Philippsen <nils@tiptoe.de>
Date: Wed, 31 Aug 2016 14:00:02 +0200
Subject: [PATCH] preserve multi-line paragraphs when extracting

---
 kajiki/i18n.py | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/kajiki/i18n.py b/kajiki/i18n.py
index e7d54cc..1b67136 100644
--- a/kajiki/i18n.py
+++ b/kajiki/i18n.py
@@ -25,5 +25,4 @@ def extract(fileobj, keywords, comment_tags, options):
     for node in ir:
         if isinstance(node, TranslatableTextNode):
             if node.text.strip():
-                for line in node.text.split('\n'):
-                    yield (node.lineno, '_', line, [])
+                yield (node.lineno, '_', node.text, [])
-- 
2.7.4
```

**Comment by nphilipp** [comment]
One thing though, doing it this way (not stripping the string) leaves the text blocks with all the leading and trailing whitespace (unlike Genshi does), which e.g. makes poedit flag all the translations if you don't manually add a leading newline when the parent tag is on the previous line like in the examples.

**Comment by amol-** [comment]
I did a quick experiment with Genshi compared to Kajiki with the proposed patch, and I'm somehow dubious about replicating Genshi logic.

This short snippet:

```
        <p>

      This page shows how you can provide multiple pages
       directly from the same controller method.  This page is generated
        from the expose decorator with the template defintion provided.
          You can provide a url with parameters and this page will display
          the parameters as html, and the json version will express
          the entries as <code>JSON</code>.
        </p>
```

As you noticed ends up being treated differently from Genshi and Kajiki:

**genshi**

```
#: plaingenshi/templates/data.html:15
msgid ""
"This page shows how you can provide multiple pages\n"
"       directly from the same controller method.  This page is generated\n"
"        from the expose decorator with the template defintion provided.\n"
"          You can provide a url with parameters and this page will display\n"
"          the parameters as html, and the json version will express\n"
"          the entries as"
```

**kajiki**

```
#: plain/templates/data.xhtml:10
msgid ""
"\n"
"\n"
"      This page shows how you can provide multiple pages\n"
"       directly from the same controller method.  This page is generated\n"
"        from the expose decorator with the template defintion provided.\n"
"          You can provide a url with parameters and this page will display\n"
"          the parameters as html, and the json version will express\n"
"          the entries as "
```

It looks like as you said Genshi strips the content of  tags. 
But should it really be doing that?

I mean the output of rendering that is totally different if `white-space: pre` is used and the template engine has now way to know how that paragraph will be used. So it seems an error to me stripping the content of a tag, the user might have actually intended to keep those new lines there (I know, it's uncommon and there are better way to do that, but still I don't expect my engine to mess with the content I wrote).

See the results:

**genshi**

![test-genshi](https://cloud.githubusercontent.com/assets/601423/18159656/040de32e-702a-11e6-8210-db33bd0c7222.png)

**kajiki**

![test-kajiki](https://cloud.githubusercontent.com/assets/601423/18159645/fa26cf92-7029-11e6-80e2-1d5764bd881c.png)

In this case it seems to me kajiki is the one doing the expected thing as it keeps the leading newlines when rendering.

Also the Genshi logic seems to be even different when extracting text and rendering, as the extracted text is totally stripped (no newlines and no spaces at begin) when generating pot files, while when rendering only the newlines are stripped and the spaces are retained.

**Comment by nphilipp** [comment]
Oh, I didn't want to express that Genshi is the be-all and end-all as far as treatment of whitespace is concerned, just that it worked better for my needs here. But I understand that it's better to play it safe and preserve whitespace on your end, maybe poedit needs to grow an option to ignore that `msgid` begins with a newline but `msgstr` doesn't.

I'm curious though how the generated HTML/XML looks like in the rendered examples above, because these two here render exactly the same for me:

* with whitespace:
```
<html><head></head><body>
    <p>

  
  
                             Hello
  
  
  
  
  
    </p>
  
</body></html>
```

* without whitespace:
```
<html><head></head><body><p>Hello</p></body></html>
```

**Comment by amol-** [comment]
The two render exactly the same as far as you don't apply CSS.

> the output of rendering that is totally different if white-space: pre is used and the template engine has no way to know how that paragraph will be used.

**Comment by amol-** [comment]
https://github.com/nandoflorestan/kajiki/commit/b152ec55aef177c5cb2bc1fd86de81541f443bcd should include changes to make this reasonable.

https://github.com/nandoflorestan/kajiki/commit/8e76c76b626cc404e94466e6c6d661150204f4fb also provides a `strip_text` option for XMLTemplate and text extractor to strip text nodes. This is `False` by default for backward compatibility. Enabling it will also produce minified html as it strips all spaces around tags.

**Comment by amol-** [comment]
https://github.com/nandoflorestan/kajiki/commit/989070c3d431bfcb88a6f235ffa2d83803d7d973 improves this further by separating empty text from text that actually needs translation.
