### ISSUE TITLE
template level variables and modules not accessible in functions

### ISSUE THREAD

**Issue by alexbodn** [nandoflorestan/kajiki#24]
hello friends,

a module imported at the level of &lt;html&gt; or &lt;body&gt;
is not accessible within a &lt;py:def&gt; function, 
even if defined in the same level

**Comment by amol-** [comment]
Probably missing `%` as stated by 

> In both of the above cases, the Python code runs in the ‘local scope’ of the template’s main rendering function, so any variables defined there will not be accessible in functions or blocks defined elsewhere in the template. To force the python block to run at ‘module-level’ in XML templates, simply prefix the first line of the Python with a percent (%) sign:

See http://kajiki.readthedocs.io/en/latest/templating-basics.html#code-blocks

**Comment by alexbodn** [comment]
thanks amol :)
