### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by jackrosenthal** [nandoflorestan/kajiki#32]
This is a feature request. I'm willing to work on this feature and submit a PR if the maintainers would find this valuable.

Essentially, it seems that on occasion it's convenient to use Kajiki from a `bash` script (or something similar) and would be convenient to have an entry point for this. For example, it could be used to format emails from `mutt`.

I was thinking of some sort of interface like this:

    kajiki [--xml] [input_file] [output_file]

`input_file` and `output_file` could default to `stdin` and `stdout` respectively.

Is this in the maintainers' interest?

**Comment by nandoflorestan** [comment]
Alessandro Molina is our current maintainer and what he says goes.

In fact, I was waiting for him to respond first, but now I'm gonna give my 2 cents.

The command-line interface is desirable software and I hope you develop it.

Although it could naturally belong in the kajiki package itself, the job can just as effectively get done by developing a separate package that depends on a certain version of Kajiki. This is probably a better solution if I am correct in assuming that Alessandro doesn't wish to maintain the command-line interface himself in the future.

But then again the command-line interface would probably be only 100 lines long or so, right?

@amol- what do you think?

**Comment by nandoflorestan** [comment]
@jackrosenthal 

When developing command-line interfaces, take a look at the following library. It might win your heart.
https://pypi.python.org/pypi/argh

**Comment by amol-** [comment]
I didn't reply quickly as I didn't have a strong opinion about it.
I can see it's something that might be useful to some people, but not needed by most kajiki users.

If I should sum up my thoughts I would say that I'm in favour of it if it's something isolated from the rest of the codebase and that doesn't involve external dependencies and more than a few lines of code. 

But experience tells me that one day it will grow to be far more than a few lines of code and so we also need to have a proper testing infrastructure for command line options to avoid breaking it while changing other parts of kajiki as it will be easily forgotten when developing other parts.

**Comment by jackrosenthal** [comment]
Why not I make a CLI (I'll try and keep it darned simple, and promise I won't add any depenencies), submit a PR, if you like it, then merge; if not, I'll just make it a separate package on PyPI?

**Comment by amol-** [comment]
@jackrosenthal I'll gladly merge it if you want to submit a Pull Request

**Comment by amol-** [comment]
fixed by #51
