### ISSUE TITLE
“Migrating from Genshi” lacks API part of migration process

### ISSUE THREAD

**Issue by vthriller** [nandoflorestan/kajiki#34]
There's not even basic things covered, like “replace `NewTextTemplate, MarkupTemplate, TemplateLoader` with `TextTemplate, XMLTemplate, FileLoader`” or “substitude `template.generate(foo=bar)` for `template(dict(foo=bar))`”.

By the way, is there any plan to bring current Kajiki APIs closer to Genshi ones? And should I report things like missing `doctype` and `serializer` options for `Template.render(…)` as separate issues here?

**Comment by amol-** [comment]
I don't think Kajiki will ever aim at simulating the Genshi API and the doctype is read directly from the source document itself (unless html output is forced).

Actually on Kajiki the paradigm is a little reversed compared to Genshi, the doctype in the source document can influence how it will be rendered.
