### ISSUE TITLE
CDATA sections not preserved

### ISSUE THREAD

**Issue by eseifert** [nandoflorestan/kajiki#6]
Unfortunately, Kajiki doesn't handle CDATA sections correctly. This causes problems with non-HTML XML documents. At the moment the CDATA markers are omitted and valid content may get translated to HTML entity references:

```python
>>> import kajiki
>>> kajiki.XMLTemplate(u'''<myxml><data><![CDATA[&gt;&#240; $foo]]></data></myxml>''')(dict(foo='bar')).render()
u'<myxml><data>&amp;gt;&amp;#240; bar</data></myxml>'
```

To avoid unexpected behavior Kajiki should preserve CDATA markers and the content of CDATA sections shouldn't be modified, except for the expansion of variables.

**Comment by amol-** [comment]
Kajiki now properly preserves CDATA sections declared by user, it is even possible to disable automatic CDATA through the ``cdata_scripts`` option of XMLTemplate.
